-- backend/migrations/seed_demo_posts.sql — DEV ONLY. Contoh post semua kemungkinan.
-- Jangan jalankan di produksi (runner menolak file seed_* di ENV=production).
-- Cara pakai (DB lokal, setelah migrate):
--   psql "$DATABASE_URL" -f backend/migrations/seed_demo_posts.sql
-- Idempoten: ON CONFLICT DO NOTHING (bisa diulang). UUID literal agar stabil.

INSERT INTO posts (id, title, body, excerpt, title_en, body_en, excerpt_en, tag, product_id, image_url, product_ids) VALUES
  ('11111111-1111-1111-1111-111111111111', 'Kenapa gula aren lebih ramah?', 'Gula aren punya indeks glikemik lebih rendah dibanding gula pasir sehingga energi lebih stabil. Cocok untuk pemanis dessert sehat Serenity.', 'Gula aren: energi stabil untuk dessert sehat.', 'Why is palm sugar friendlier?', 'Palm sugar has a lower glycemic index than white sugar, so energy stays stable. A fit sweetener for Serenity''s healthy desserts.', 'Palm sugar: stable energy for healthy desserts.', 'FunFact', NULL, '/images/post_gula_aren.jpg', ARRAY['samp_001', 'samp_003']),
  ('22222222-2222-2222-2222-222222222222', 'Minum air putih sebelum makan', 'Minum segelas air putih 30 menit sebelum makan membantu mengontrol porsi makan dan menjaga hidrasi sepanjang hari.', NULL, 'Drink water before meals', 'A glass of water 30 minutes before meals helps control portions and keeps you hydrated all day.', NULL, 'FunFact', NULL, NULL, '{}'),
  ('33333333-3333-3333-3333-333333333333', 'Serenity buka pre-order weekend', 'Mulai minggu ini Serenity menerima pre-order khusus weekend. Pesan maksimal H-1, ambil sendiri atau diantar.', 'Pre-order weekend telah dibuka.', 'Serenity opens weekend pre-orders', 'Starting this week Serenity takes weekend-only pre-orders. Order by H-1 at the latest, pick up or get it delivered.', 'Weekend pre-orders are now open.', 'News', NULL, NULL, ARRAY['samp_002']),
  ('44444444-4444-4444-4444-444444444444', 'Varian baru: Puding Chia Mangga', 'Puding chia dengan mangga asli tanpa pengawet kini tersedia setiap hari selama persediaan masih ada.', NULL, 'New: Mango Chia Pudding', 'Chia pudding with real mango and no preservatives is now available daily while stock lasts.', NULL, 'News', NULL, '/images/post_puding.jpg', '{}'),
  ('55555555-5555-5555-5555-555555555555', 'Riset: protein bantu kenyang lebih lama', 'Penelitian menunjukkan asupan protein cukup saat sarapan membuat kenyang lebih lama dan mengurangi ngemil berlebih.', 'Protein saat sarapan menekan ngemil berlebih.', 'Research: protein keeps you full longer', 'Research shows enough protein at breakfast keeps you full longer and cuts excess snacking.', 'Breakfast protein curbs excess snacking.', 'Research', NULL, '/images/post_protein.jpg', ARRAY['samp_004']),
  ('66666666-6666-6666-6666-666666666666', 'Riset: serat dan gula darah', 'Asupan serat larut membantu memperlambat penyerapan gula sehingga kadar gula darah lebih stabil setelah makan.', NULL, 'Research: fiber and blood sugar', 'Soluble fiber slows sugar absorption so blood sugar stays steadier after meals.', NULL, 'Research', NULL, NULL, ARRAY['samp_005'])
ON CONFLICT (id) DO NOTHING;
